/**
 * The `README.md` of a generated Space.
 *
 * On Hugging Face the README is not documentation, it is configuration: the YAML
 * front matter is what tells the Hub this is a static Space and what to put on the
 * card. Get the front matter wrong and the Space does not build; the prose below it
 * is for the human who inherits the repo.
 *
 * V1 asks the Hub for NOTHING beyond a static build. No `hf_oauth`, no scopes, no
 * sign-in: the generated Space runs the model in the visitor's own browser, so it
 * needs no account, no token and costs nobody anything. (The configurator still
 * signs its user in — to read a private model and to push the Space — but none of
 * that reaches the artefact this file describes.)
 */

import { APARTE_VERSION, DEFAULT_CONFIG, isValidRepoId } from '../config/space-config';
import type { Lang } from '../i18n/lang';
import {
  SPACES_URL,
  bakedLang,
  carriesBothLangs,
  fill,
  spaceHeading,
  type SpaceConfigWithWeights,
} from './index-html';

// ── What the README says ───────────────────────────────────────────────────

/**
 * The prose of the README, in the language the Space was generated in.
 *
 * Same rule as the page's own copy, for the same reason: ENGLISH IS THE SOURCE AND IT
 * DEFINES THE TYPE, so a French block that goes missing is a compile error and not a
 * hole in somebody's repository. `{named}` holes, filled by `fill()`; whole sentences,
 * never fragments.
 *
 * What is NOT in here is the front matter. `title:`, `emoji:`, `colorFrom:`, `sdk:` and
 * the rest are keys the Hub parses, not words anybody reads — translating one would
 * stop the Space from building. The badge line is the same: it is a URL and an image.
 */
const readmeCopyEn = {
  intro: 'An AI chat built with [aparté](https://apartejs.dev), generated by\n[Aparté Spaces]({spaces}).',
  summary:
    "It runs {model} **entirely in the visitor's browser** through [Transformers.js](https://huggingface.co/docs/transformers.js) — WebGPU where it is available, WASM otherwise. There is no API, no key and no server: the weights download once and are kept in the browser's cache.",
  /** Only on a Space that ships both languages. One line, as promised. */
  bilingual:
    "The page is written in English and in French and follows each visitor's own browser;\nwhen it cannot tell, it speaks {fallback}. Set the `LANG` variable to `en` or `fr` to\npin it.",
  /**
   * The languages, named mid-sentence rather than on a label.
   *
   * `LANG_ENDONYM` is the wrong tool here and the difference is not pedantry: it is a
   * picker's label, capitalised as one, and French does not capitalise a language
   * inside a sentence — "elle parle Français" is wrong where "elle parle français" is
   * right. English capitalises both. So each table names both languages in its own
   * words, and the sentence stays grammatical either way round.
   */
  langNames: { en: 'English', fr: 'French' },
  /** The model, when there is none to link to. */
  notSet: '_(not set)_',
  noAccountHeading: 'No account, no token, no bill',
  noAccount:
    "Nobody has to sign in to use this Space, and nothing about it is metered. A visitor\nopens the page, the model's weights are downloaded from the public Hub straight into\ntheir browser on the first click of **Load the model**, and every answer after that\nis computed on their own machine. No request carries a token, because there is no\ntoken: nothing is billed to you and nothing is billed to them.",
  gated:
    'The one thing that would still need authentication is the **weights themselves** — a\nprivate or gated repository is not downloadable by an anonymous browser, and this\npage has no way to sign one in. Point `MODEL_ID` at a public repository.',
  changingHeading: 'Changing it without editing the code',
  changing:
    "Everything the chat says and shows is read from this Space's **variables** at load\ntime, and only falls back to what was baked into `index.html` when a variable is not\nset. So the usual changes are made in **Settings → Variables and secrets → New\nvariable**, and take effect on the next reload.",
  tableHead: '| Variable | What it changes | Generated with |',
  varTitle: 'The heading and the browser tab.',
  varModel: 'The model the chat uses.',
  varSystemPrompt: 'The instructions sent ahead of every conversation.',
  varGreeting: 'The line shown above the composer before the first message.',
  varAccent: 'Brand colour, as a hex value (for example `#FF3E00`).',
  varLang: 'The language the page speaks — `en` or `fr`. Unset, it follows the visitor.',
  empty: '_(empty)_',
  secrets:
    '> Variables are **public** — anyone who opens the Space can read them. Never put a\n> token in one.',
  downloadHeading: 'About the download',
  download:
    "The model is fetched on the visitor's first click on **Load the model** and then kept\nin the browser's Cache API, so a returning visitor pays for it once. Nothing is sent\nanywhere: generation happens on their machine, off the main thread in a Web Worker.",
  onnx: 'A model only runs here if it has been converted to ONNX — look for an `onnx/` folder\nin the repository. If yours has not been, the [onnx-community](https://huggingface.co/onnx-community)\norganisation has already converted a great many, and [🤗 Optimum](https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model)\nconverts the rest in one command.',
  contentsHeading: 'What is in here',
  contents:
    "`index.html` is the whole application: one standalone document, no build step and no\nnpm. It loads [`@aparte/core`](https://apartejs.dev) and its provider from jsDelivr,\npinned at `{version}` on every URL — pinned rather than floating so this Space\nkeeps behaving the way it does today. Edit it in the Hub's file editor and the change\nis live as soon as it is committed.",
  licenceHeading: 'Licence',
  licence: 'Yours. aparté itself is MIT.',
};

/** The type the French README has to satisfy. */
export type ReadmeCopy = typeof readmeCopyEn;

/**
 * The same README in French, written as French rather than transposed from English.
 *
 * The Hub's own settings UI stays in its own words — **Settings → Variables and
 * secrets** is a path somebody has to find on an English screen, and translating it
 * would send them looking for a menu that does not exist.
 *
 * No-break spaces are written `\u00a0` rather than typed, so they stay visible in this
 * file: French puts one before `:` and before `;`.
 */
const readmeCopyFr: ReadmeCopy = {
  intro: 'Un chat IA construit avec [aparté](https://apartejs.dev), généré par\n[Aparté Spaces]({spaces}).',
  summary:
    'Il fait tourner {model} **entièrement dans le navigateur du visiteur**, via [Transformers.js](https://huggingface.co/docs/transformers.js) — WebGPU quand il est disponible, WASM sinon. Ni API, ni clé, ni serveur\u00a0: les poids se téléchargent une fois et restent dans le cache du navigateur.',
  bilingual:
    'La page est écrite en français et en anglais, et suit le navigateur de chaque\nvisiteur\u00a0; quand elle ne peut pas savoir, elle parle {fallback}. Mets la variable\n`LANG` à `en` ou `fr` pour la figer.',
  langNames: { en: 'anglais', fr: 'français' },
  notSet: '_(non défini)_',
  noAccountHeading: 'Ni compte, ni jeton, ni facture',
  noAccount:
    'Personne n’a besoin de se connecter pour utiliser ce Space, et rien n’y est facturé à\nl’usage. Un visiteur ouvre la page, les poids du modèle sont téléchargés depuis le Hub\npublic directement dans son navigateur au premier clic sur **Charger le modèle**, et\nchaque réponse est ensuite calculée sur sa propre machine. Aucune requête ne porte de\njeton, parce qu’il n’y en a pas\u00a0: rien ne t’est facturé et rien ne lui est facturé.',
  gated:
    'La seule chose qui demanderait encore une authentification, ce sont les **poids\neux-mêmes** — un dépôt privé ou sous conditions n’est pas téléchargeable par un\nnavigateur anonyme, et cette page n’a aucun moyen de s’y connecter. Fais pointer\n`MODEL_ID` vers un dépôt public.',
  changingHeading: 'Le modifier sans toucher au code',
  changing:
    'Tout ce que le chat dit et montre est lu dans les **variables** de ce Space au\nchargement\u00a0; il ne retombe sur ce qui est inscrit dans `index.html` que si la variable\nn’est pas définie. Les changements courants se font donc dans **Settings → Variables\nand secrets → New variable**, et prennent effet au rechargement suivant.',
  tableHead: '| Variable | Ce qu’elle change | Valeur à la génération |',
  varTitle: 'Le titre affiché et l’onglet du navigateur.',
  varModel: 'Le modèle utilisé par le chat.',
  varSystemPrompt: 'Les instructions envoyées avant chaque conversation.',
  varGreeting: 'La ligne affichée au-dessus du composer avant le premier message.',
  varAccent: 'Couleur de marque, en hexadécimal (par exemple `#FF3E00`).',
  varLang: 'La langue de la page — `en` ou `fr`. Non définie, elle suit le visiteur.',
  empty: '_(vide)_',
  secrets:
    '> Les variables sont **publiques** — n’importe qui ouvrant ce Space peut les lire.\n> N’y mets jamais de jeton.',
  downloadHeading: 'À propos du téléchargement',
  download:
    'Le modèle est récupéré au premier clic du visiteur sur **Charger le modèle**, puis\ngardé dans le Cache API du navigateur\u00a0: un visiteur qui revient ne le paie qu’une\nfois. Rien n’est envoyé nulle part — la génération se fait sur sa machine, hors du fil\nprincipal, dans un Web Worker.',
  onnx: 'Un modèle ne tourne ici que s’il a été converti en ONNX — cherche un dossier `onnx/`\ndans le dépôt. Si ce n’est pas le cas du tien, l’organisation [onnx-community](https://huggingface.co/onnx-community)\nen a déjà converti un grand nombre, et [🤗 Optimum](https://huggingface.co/docs/optimum/exporters/onnx/usage_guides/export_a_model)\nconvertit le reste en une seule commande.',
  contentsHeading: 'Ce qu’il y a dedans',
  contents:
    '`index.html` est toute l’application\u00a0: un document autonome, sans étape de build et\nsans npm. Il charge [`@aparte/core`](https://apartejs.dev) et son provider depuis\njsDelivr, épinglés à `{version}` sur chaque URL — épinglés plutôt que flottants pour\nque ce Space continue de se comporter comme aujourd’hui. Modifie-le dans l’éditeur de\nfichiers du Hub et le changement est en ligne dès qu’il est commité.',
  licenceHeading: 'Licence',
  licence: 'La tienne. aparté lui-même est sous licence MIT.',
};

const README_COPY: Record<Lang, ReadmeCopy> = { en: readmeCopyEn, fr: readmeCopyFr };

/**
 * The Hub validates the card gradient against a fixed palette and refuses to build
 * on anything else, so an unknown colour falls back rather than breaking the Space.
 */
const HF_COLOURS = [
  'red',
  'yellow',
  'green',
  'blue',
  'indigo',
  'purple',
  'pink',
  'gray',
] as const;

function safeColour(value: string, fallback: string): string {
  const colour = value.trim().toLowerCase();
  return (HF_COLOURS as readonly string[]).includes(colour) ? colour : fallback;
}

/**
 * One emoji, or the default.
 *
 * `emoji:` is a card field like the colours, and it was the only one taking user
 * input on trust — a sentence, a newline or a stray `"` would land in the front
 * matter and the card would carry whatever was typed. So: one pictographic
 * grapheme (a base, with the variation selectors, skin-tone modifiers and
 * ZWJ-joined parts that make up a single glyph), nothing else.
 */
const EMOJI_GRAPHEME =
  /^\p{Extended_Pictographic}(?:[\uFE0E\uFE0F\u{1F3FB}-\u{1F3FF}]|\u200D\p{Extended_Pictographic}[\uFE0E\uFE0F\u{1F3FB}-\u{1F3FF}]?)*$/u;

/** A four-person family with skin tones is 19 UTF-16 units; nothing legitimate is longer. */
const EMOJI_MAX_LENGTH = 24;

export function safeEmoji(value: string): string {
  const emoji = value.trim();
  if (!emoji || emoji.length > EMOJI_MAX_LENGTH) return DEFAULT_CONFIG.emoji;
  return EMOJI_GRAPHEME.test(emoji) ? emoji : DEFAULT_CONFIG.emoji;
}

/**
 * A double-quoted YAML scalar.
 *
 * Quoted rather than bare because a title is user input: a leading `#`, a `: `, a
 * `[` or a stray newline all mean something to a YAML parser and none of them mean
 * it here. Inside double quotes only `\` and `"` need escaping, and control
 * characters have to go — a newline in a title would end the value.
 */
export function yamlString(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/[\u0000-\u001f\u007f]/g, ' ')
    .trim();
  return `"${escaped}"`;
}

/**
 * A user value that is about to sit inside a Markdown code span.
 *
 * Three things end a span early, and all three are ordinary in the values this
 * README shows: a backtick closes it, a newline ends the block it is in (a
 * multi-line SYSTEM_PROMPT used to shred the variables table and every row under
 * it), and a `|` splits a table row into extra cells. One helper, used everywhere
 * a value is rendered, rather than a different half-escape at each call site.
 */
function codeSpan(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/`/g, "'")
    .replace(/\|/g, '\\|');
}

/**
 * The model, linked to its Hub page when the id is one the Hub could have.
 *
 * A Markdown link destination ends at the first `)`, so an id that is not a repo id
 * is shown as a code span and not linked at all — `isValidRepoId` allows only
 * `owner/name` out of word characters, dots and dashes, which is exactly the set
 * that survives a URL untouched.
 */
function modelReference(modelId: string, copy: ReadmeCopy): string {
  const shown = codeSpan(modelId);
  if (!shown) return copy.notSet;
  if (!isValidRepoId(modelId)) return `\`${shown}\``;
  return `[\`${shown}\`](https://huggingface.co/${modelId.trim()})`;
}

/**
 * The table of Space variables the owner can set without touching the code.
 *
 * `LANG` appears only on a Space that carries both languages, because that is the only
 * Space where it can do anything: a page baked in one language has no second set of
 * strings to switch to, and documenting a variable that cannot work is the paper
 * version of offering a button that cannot work.
 */
function variablesTable(config: SpaceConfigWithWeights, copy: ReadmeCopy): string {
  const rows: Array<[string, string, string]> = [
    ['`TITLE`', copy.varTitle, config.title],
    ['`MODEL_ID`', copy.varModel, config.modelId],
    ['`SYSTEM_PROMPT`', copy.varSystemPrompt, config.systemPrompt],
    ['`GREETING`', copy.varGreeting, config.greeting],
    ['`ACCENT`', copy.varAccent, config.accent],
  ];

  if (carriesBothLangs(config)) rows.push(['`LANG`', copy.varLang, '']);

  const body = rows
    .map(([name, purpose, current]) => {
      const value = codeSpan(current);
      return `| ${name} | ${purpose} | ${value ? `\`${value}\`` : copy.empty} |`;
    })
    .join('\n');

  return `${copy.tableHead}
| --- | --- | --- |
${body}`;
}

/**
 * The front matter plus the prose.
 *
 * The prose follows `config.lang`. `both` gets the CREATOR's language and one extra
 * line saying the page adapts to its visitor — a README is read by whoever inherits
 * the repository, and that is one person, not a worldwide audience; there is nothing
 * to gain from writing it twice.
 *
 * The front matter and the badge line are untouched by any of this. They are Hub
 * configuration and a URL, not words anybody reads.
 */
export function generateReadme(config: SpaceConfigWithWeights): string {
  const title = spaceHeading(config);
  const lang = bakedLang(config);
  const copy = README_COPY[lang];

  const frontMatter = [
    '---',
    `title: ${yamlString(title)}`,
    `emoji: ${yamlString(safeEmoji(config.emoji))}`,
    `colorFrom: ${safeColour(config.colorFrom, 'indigo')}`,
    `colorTo: ${safeColour(config.colorTo, 'purple')}`,
    'sdk: static',
    'pinned: false',
    '---',
  ];

  const badgeLine = config.badge
    ? `\n[![Made with Aparté Spaces](${SPACES_URL}/badge.svg)](${SPACES_URL})\n`
    : '';

  const bilingualLine = carriesBothLangs(config)
    ? `\n${fill(copy.bilingual, { fallback: copy.langNames[lang] })}\n`
    : '';

  return `${frontMatter.join('\n')}

# ${title}

${fill(copy.intro, { spaces: SPACES_URL })}

${fill(copy.summary, { model: modelReference(config.modelId, copy) })}
${bilingualLine}${badgeLine}
## ${copy.noAccountHeading}

${copy.noAccount}

${copy.gated}

## ${copy.changingHeading}

${copy.changing}

${variablesTable(config, copy)}

${copy.secrets}

### ${copy.downloadHeading}

${copy.download}

${copy.onnx}

## ${copy.contentsHeading}

${fill(copy.contents, { version: APARTE_VERSION })}

## ${copy.licenceHeading}

${copy.licence}
`;
}
