<script lang="ts">
  /**
   * The windshield: an iframe that is HONEST about how wide it is.
   *
   * The problem this exists to solve. A "tablet" button that squeezes a 400px pane down
   * to look tablet-shaped is a lie twice over: the document inside still reports the
   * pane's width, so its own media queries fire at the wrong breakpoint, and whatever
   * you judge on that glass is not what a tablet will show. A preview you cannot trust
   * is worse than no preview, because you stop checking.
   *
   * So the size is given to the DOCUMENT and only the PICTURE is scaled. The iframe is
   * laid out at its real pixel size — 768 wide means the element is 768 CSS pixels wide —
   * and a `transform: scale()` on the wrapper around it shrinks the rendered result to
   * fit the pane. A transform does not change layout, so the frame's own viewport stays
   * 768: `matchMedia('(max-width: 480px)')` inside it answers exactly as it would on the
   * device. The zoom percentage is then a fact about the picture, and it is printed next
   * to the size so nobody mistakes one for the other.
   *
   * Everything here is a LENS. This component never sees `SpaceConfig` and never touches
   * the generated bytes; it is handed a sandbox string and a title, and it hands back the
   * iframe element through `bind:frame` for the owner to navigate. Resizing the glass
   * cannot change the Space, by construction — there is nothing here to change it with.
   *
   *     <Viewport bind:frame {sandbox} title="Live preview" {busy} onload={…}>
   *       … overlays drawn on the glass …
   *     </Viewport>
   */
  import type { Snippet } from 'svelte';

  import { lang } from '../lib/i18n/store.svelte';
  import { uiCopy } from '../lib/i18n/ui';

  interface Props {
    /** The iframe element, handed back so the owner can navigate it. */
    frame?: HTMLIFrameElement | null;
    /** Sandbox tokens. Decided by the owner — this component only renders them. */
    sandbox: string;
    /** The iframe's accessible name. Required: an untitled frame is a dead end. */
    title: string;
    /** Permissions policy for the frame, e.g. `clipboard-write`. */
    allow?: string;
    /** The owner is rebuilding; the glass steps back rather than flashing. */
    busy?: boolean;
    onload?: () => void;
    /** Drawn over the glass — a failure card, a readout. Never over the bar. */
    children?: Snippet;
  }

  let {
    frame = $bindable(null),
    sandbox,
    title,
    allow,
    busy = false,
    onload,
    children,
  }: Props = $props();

  /**
   * The words on this panel, in whichever language the configurator is speaking.
   *
   * `lang.current` is read here, inside a `$derived`, which is what subscribes this
   * component to it: a language switch re-runs this and every label, `aria-label` and
   * `title` below it changes with it — including the live region, which is the only way a
   * screen-reader user hears the glass move.
   */
  const t = $derived(uiCopy(lang.current));

  /**
   * Sizes, not devices.
   *
   * "iPhone 14 Pro" would be a promise this cannot keep: no notch, no mobile Safari, no
   * touch. These are round numbers with plain names, which is all the preview can
   * honestly claim — the width is real, and nothing else is being simulated.
   *
   * The NUMBERS live here and the NAMES live in the dictionary: this table is a fact
   * about pixels and does not change with the language.
   */
  type Preset = 'mobile' | 'tablet' | 'laptop' | 'fill';

  const PRESETS: { value: Preset; width: number; height: number }[] = [
    { value: 'mobile', width: 375, height: 667 },
    { value: 'tablet', width: 768, height: 1024 },
    { value: 'laptop', width: 1280, height: 800 },
    // Fill carries no numbers of its own: it is whatever the pane happens to be.
    { value: 'fill', width: 0, height: 0 },
  ];

  /** A percentage is a number in every language; only `fit` is a word, so only it is null. */
  const ZOOMS: { value: 'fit' | number; label: string | null }[] = [
    { value: 'fit', label: null },
    { value: 0.5, label: '50%' },
    { value: 0.75, label: '75%' },
    { value: 1, label: '100%' },
  ];

  /** The gasket: the padded rubber seal between the glass and the hull, in stage pixels. */
  const GASKET = 8;
  /** The bezel's hairline, on both sides. */
  const EDGE = 1;
  /** What the frame loses to its own housing, horizontally and vertically. */
  const CHROME = 2 * (GASKET + EDGE);

  const MIN_W = 240;
  const MIN_H = 200;
  const MAX = 4096;

  let stage = $state<HTMLElement | null>(null);
  let stageW = $state(0);
  let stageH = $state(0);

  /** `custom` is not a button: it is where a drag leaves you. */
  let preset = $state<Preset | 'custom'>('fill');
  /** The chosen document size, in real pixels. Meaningless while `fill` is on. */
  let sizeW = $state(375);
  let sizeH = $state(667);
  let zoom = $state<'fit' | number>('fit');

  let panning = $state(false);
  let resizing = $state(false);

  const isFill = $derived(preset === 'fill');

  /** What is left for the document once the housing has taken its share. */
  const availW = $derived(Math.max(1, stageW - CHROME));
  const availH = $derived(Math.max(1, stageH - CHROME));

  /**
   * The document's real viewport, in CSS pixels. This number is not a wish: it is put
   * straight onto the iframe's `width`/`height`, and it is what the page inside measures.
   */
  const frameW = $derived(isFill ? availW : sizeW);
  const frameH = $derived(isFill ? availH : sizeH);

  const fitScale = $derived(Math.min(1, availW / frameW, availH / frameH));
  /** Fill is by definition 1:1 — there is nothing to fit it into but itself. */
  const scale = $derived(isFill ? 1 : zoom === 'fit' ? fitScale : zoom);
  const percent = $derived(Math.round(scale * 100));

  /** The housing's size on the stage — the picture, plus the gasket and the hairline. */
  const bezelW = $derived(frameW * scale + CHROME);
  const bezelH = $derived(frameH * scale + CHROME);
  /** Half a pixel of slack: a bezel exactly as wide as the stage is not overflowing. */
  const overflowing = $derived(bezelW > stageW + 0.5 || bezelH > stageH + 0.5);

  /**
   * The one sentence a screen-reader user needs after touching any control here.
   * Spelled out rather than glyphed: "768 × 1024" is read as "768 by 1024" by some
   * screen readers and as "768 times 1024" by others, and neither is wrong.
   */
  const readout = $derived(`${Math.round(frameW)} × ${Math.round(frameH)} · ${percent} %`);
  const spokenSize = $derived(
    t.viewport.spokenSize(Math.round(frameW), Math.round(frameH), percent),
  );

  /**
   * What the live region actually holds — the SETTLED size, not every frame of a drag.
   *
   * A resize drag changes the size a hundred times in a second, and a polite live region
   * fed a hundred sentences is a screen reader talking over itself for as long as the
   * mouse is down. So the announcement is held while a drag is in flight and made once
   * when it ends: the early return keeps the value put, and the run triggered by
   * `resizing` going false publishes the number the user stopped on. A click on a preset
   * or a zoom is announced immediately, because there is nothing to settle.
   */
  let announced = $state('');

  $effect(() => {
    // All three read before the branch, so `||` short-circuiting cannot leave one of the
    // flags out of the dependency set and strand the announcement.
    const next = spokenSize;
    const dragging = resizing;
    const sliding = panning;
    if (dragging || sliding) return;
    announced = next;
  });

  function clampW(value: number): number {
    return Math.round(Math.min(MAX, Math.max(MIN_W, value)));
  }

  function clampH(value: number): number {
    return Math.round(Math.min(MAX, Math.max(MIN_H, value)));
  }

  function choose(next: Preset): void {
    const found = PRESETS.find((entry) => entry.value === next);
    if (found && next !== 'fill') {
      sizeW = found.width;
      sizeH = found.height;
    }
    preset = next;
  }

  /**
   * Leave whatever preset is on, keeping the size the eye is currently looking at.
   *
   * Dragging out of `fill` has to seed the numbers from the pane, or the frame would
   * jump to a stale 375 the moment the handle moves one pixel.
   */
  function detach(): void {
    if (isFill) {
      sizeW = clampW(frameW);
      sizeH = clampH(frameH);
    }
    preset = 'custom';
  }

  function rotate(): void {
    detach();
    const width = sizeW;
    sizeW = clampW(sizeH);
    sizeH = clampH(width);
  }

  /**
   * A resize drag.
   *
   * Two details that are easy to get wrong. The bezel is CENTRED, so the edge under the
   * cursor only moves half of whatever the size changes by — hence the factor of two.
   * And the drag is in STAGE pixels while the size is in DOCUMENT pixels, so the delta is
   * divided by the scale: at 25% the hand moves a quarter as far as the number does.
   *
   * The delta is taken from the previous move rather than from the start of the drag, so
   * that a live `Fit` zoom — which changes the scale as the frame grows — stays stable
   * instead of fighting the arithmetic.
   */
  /**
   * Pointer capture is an OPTIMISATION here, never the mechanism.
   *
   * `setPointerCapture` throws `NotFoundError` for any pointer the browser does not
   * consider active — and it is the first thing a drag wants to do, so a throw there kills
   * the whole gesture before a single listener is attached. The drag therefore listens on
   * the WINDOW, which receives the moves whether or not the capture took, and keeps
   * following the cursor when it leaves the frame's edge or the page entirely.
   */
  function capture(element: HTMLElement, pointerId: number): () => void {
    try {
      element.setPointerCapture(pointerId);
    } catch {
      return () => {};
    }
    return () => {
      try {
        if (element.hasPointerCapture(pointerId)) element.releasePointerCapture(pointerId);
      } catch {
        // The pointer is already gone; there is nothing left to release.
      }
    };
  }

  function beginResize(event: PointerEvent, axis: 'e' | 's' | 'se'): void {
    if (event.button !== 0) return;
    // The stage is listening for a pan; a drag on a grip is not one.
    event.stopPropagation();
    event.preventDefault();

    const release = capture(event.currentTarget as HTMLElement, event.pointerId);
    detach();
    resizing = true;

    let lastX = event.clientX;
    let lastY = event.clientY;

    const move = (moved: PointerEvent): void => {
      if (moved.pointerId !== event.pointerId) return;
      const factor = 2 / (scale || 1);
      if (axis !== 's') sizeW = clampW(sizeW + (moved.clientX - lastX) * factor);
      if (axis !== 'e') sizeH = clampH(sizeH + (moved.clientY - lastY) * factor);
      lastX = moved.clientX;
      lastY = moved.clientY;
    };

    const end = (ended: PointerEvent): void => {
      if (ended.pointerId !== event.pointerId) return;
      resizing = false;
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', end);
      window.removeEventListener('pointercancel', end);
      release();
    };

    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', end);
    window.addEventListener('pointercancel', end);
  }

  /** The same handles, from the keyboard. Ten pixels a press, one with Shift. */
  function gripKey(event: KeyboardEvent, axis: 'e' | 's' | 'se'): void {
    const step = event.shiftKey ? 1 : 10;
    const horizontal = axis !== 's';
    const vertical = axis !== 'e';

    let handled = true;
    if (horizontal && event.key === 'ArrowRight') {
      detach();
      sizeW = clampW(sizeW + step);
    } else if (horizontal && event.key === 'ArrowLeft') {
      detach();
      sizeW = clampW(sizeW - step);
    } else if (vertical && event.key === 'ArrowDown') {
      detach();
      sizeH = clampH(sizeH + step);
    } else if (vertical && event.key === 'ArrowUp') {
      detach();
      sizeH = clampH(sizeH - step);
    } else {
      handled = false;
    }

    if (handled) event.preventDefault();
  }

  /**
   * Click-drag panning, when the picture is bigger than the pane.
   *
   * Implemented as `scrollLeft`/`scrollTop` on the stage rather than as a transform, so
   * the wheel, the trackpad, the scrollbars and Page Up all move the same view for free —
   * and so a keyboard user is never stranded in a corner of an oversized frame.
   *
   * The listener is on the STAGE, and that is deliberate: a pointerdown inside the iframe
   * belongs to another document and never reaches us, which is exactly right. The
   * previewed page keeps every one of its own clicks; the gasket around it is the grab
   * handle, and it is on all four sides.
   */
  function beginPan(event: PointerEvent): void {
    const element = stage;
    if (!element || !overflowing || event.button !== 0) return;
    event.preventDefault();

    const startX = event.clientX;
    const startY = event.clientY;
    const fromLeft = element.scrollLeft;
    const fromTop = element.scrollTop;
    const release = capture(element, event.pointerId);
    panning = true;

    const move = (moved: PointerEvent): void => {
      if (moved.pointerId !== event.pointerId) return;
      element.scrollLeft = fromLeft - (moved.clientX - startX);
      element.scrollTop = fromTop - (moved.clientY - startY);
    };

    const end = (ended: PointerEvent): void => {
      if (ended.pointerId !== event.pointerId) return;
      panning = false;
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', end);
      window.removeEventListener('pointercancel', end);
      release();
    };

    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', end);
    window.addEventListener('pointercancel', end);
  }
</script>

<div class="viewport">
  <!-- The instrument strip for the glass itself. Size, orientation and zoom are three
       different questions, so they are three groups with three etched labels rather than
       one row of ten buttons. The labels are `aria-hidden`: each group already carries a
       real `aria-label`, and a screen reader does not need the word twice. -->
  <div class="viewport__bar">
    <div class="viewport__gauge">
      <span class="viewport__label" aria-hidden="true">{t.viewport.sizeLabel}</span>
      <div class="aparte-btn-group" role="group" aria-label={t.viewport.sizeGroup}>
        {#each PRESETS as option (option.value)}
          {@const label = t.viewport.presets[option.value]}
          <button
            type="button"
            class="aparte-btn aparte-btn--sm aparte-btn--surface"
            aria-pressed={preset === option.value}
            aria-label={option.value === 'fill'
              ? t.viewport.fillOption
              : t.viewport.presetOption(label, option.width, option.height)}
            title={option.value === 'fill'
              ? t.viewport.fillHint
              : `${option.width} × ${option.height}`}
            onclick={() => choose(option.value)}
          >
            {label}
          </button>
        {/each}
      </div>
    </div>

    <!-- Meaningless while the frame is the pane, so it is disabled rather than hidden:
         a control that vanishes teaches nothing about why. -->
    <button
      type="button"
      class="aparte-btn aparte-btn--sm aparte-btn--surface viewport__rotate"
      disabled={isFill}
      aria-label={t.viewport.rotateOption}
      title={t.viewport.rotate}
      onclick={rotate}
    >
      <span aria-hidden="true">⟳</span>
    </button>

    <div class="viewport__gauge">
      <span class="viewport__label" aria-hidden="true">{t.viewport.zoomLabel}</span>
      <div class="aparte-btn-group" role="group" aria-label={t.viewport.zoomGroup}>
        {#each ZOOMS as option (String(option.value))}
          {@const label = option.label ?? t.viewport.zoomFit}
          <button
            type="button"
            class="aparte-btn aparte-btn--sm aparte-btn--surface"
            disabled={isFill}
            aria-pressed={!isFill && zoom === option.value}
            aria-label={option.value === 'fit'
              ? t.viewport.zoomFitOption
              : t.viewport.zoomOption(label)}
            onclick={() => (zoom = option.value)}
          >
            {label}
          </button>
        {/each}
      </div>
    </div>

    <!--
      The one number on the panel that is a measurement, so: the data face, tabular, and
      live. A size change made with the mouse or a drag handle is announced here, and it
      is the only way a screen-reader user finds out that the glass moved.

      Two texts, not one, and NOT an `aria-label` on the region. A live region announces
      its CONTENT when the content changes; an `aria-label` names the region and is not
      what gets read out, so labelling it and hiding its only child would leave a live
      region with nothing to say. Instead the glyph version is `aria-hidden` for the eye,
      and a spoken version is off-screen for the ear — "768 × 1024 · 47 %" is read as
      "768 times 1024 middle dot 47 percent" by at least one screen reader, which is not
      a sentence anybody wants twice a second.
    -->
    <p class="viewport__readout" aria-live="polite">
      <span aria-hidden="true">{readout}</span>
      <span class="viewport__spoken">{announced}</span>
    </p>
  </div>

  <div class="viewport__area">
    <!-- The stage takes a pointerdown so the frame can be dragged into view, and it is
         deliberately NOT a control: it is a scroll container, and scroll containers are
         already reachable from the keyboard (Tab into it, then arrows, Page Up, Home).
         Giving it a role and a tabindex would announce a "button" that does nothing on
         Enter and would shadow the real controls in the strip above. -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      bind:this={stage}
      class="viewport__stage"
      class:is-pannable={overflowing}
      class:is-panning={panning}
      bind:clientWidth={stageW}
      bind:clientHeight={stageH}
      onpointerdown={beginPan}
    >
      <!-- The housing. The hairline and the shadow live HERE, on an element measured in
           stage pixels, and not on the scaled wrapper inside it — a 1px border under a
           0.25 scale would render as a quarter of a pixel and the frame would dissolve
           into the grid at every zoom below 100%. Out here the edge is one crisp pixel at
           every zoom, which is what stops the shrunken state from looking broken. -->
      <div
        class="viewport__bezel"
        class:is-fill={isFill}
        style:width="{bezelW}px"
        style:height="{bezelH}px"
      >
        <div
          class="viewport__glass"
          style:width="{frameW}px"
          style:height="{frameH}px"
          style:transform="scale({scale})"
        >
          <iframe
            bind:this={frame}
            class="viewport__frame"
            class:is-busy={busy}
            class:is-inert={resizing || panning}
            {title}
            {sandbox}
            {allow}
            src="about:blank"
            {onload}
          ></iframe>
        </div>

        {#if !isFill}
          <!-- Three real buttons, on the housing rather than on the picture: they keep
               their full size at every zoom without a counter-scale, and they are
               operable from the keyboard, which a bare drag target never is. -->
          <button
            type="button"
            class="viewport__grip viewport__grip--e"
            aria-label={t.viewport.gripWidth}
            title={t.viewport.gripWidthHint}
            onpointerdown={(event) => beginResize(event, 'e')}
            onkeydown={(event) => gripKey(event, 'e')}
          ></button>
          <button
            type="button"
            class="viewport__grip viewport__grip--s"
            aria-label={t.viewport.gripHeight}
            title={t.viewport.gripHeightHint}
            onpointerdown={(event) => beginResize(event, 's')}
            onkeydown={(event) => gripKey(event, 's')}
          ></button>
          <button
            type="button"
            class="viewport__grip viewport__grip--se"
            aria-label={t.viewport.gripBoth}
            title={t.viewport.gripBothHint}
            onpointerdown={(event) => beginResize(event, 'se')}
            onkeydown={(event) => gripKey(event, 'se')}
          ></button>
        {/if}
      </div>
    </div>

    <!-- Drawn on the glass, outside the scroller so it does not pan away with it. -->
    <div class="viewport__overlay">{@render children?.()}</div>
  </div>
</div>

<style>
  .viewport {
    /* The kit's controls read aparté's ink tokens; this product remaps the surfaces but
       not the text, so they are fed here to stay legible on the hull. */
    --aparte-text: var(--ink, #ece8f1);
    --aparte-text-muted: var(--ink-dim, #a79fb5);

    display: flex;
    flex-direction: column;
    min-width: 0;
    min-height: 0;
    height: 100%;
    background: var(--void, #070a12);
  }

  /* ── The strip ─────────────────────────────────────────────────────────── */

  .viewport__bar {
    display: flex;
    align-items: center;
    gap: 0.5rem 0.75rem;
    flex-wrap: wrap;
    flex: none;
    padding: 0.4rem 0.6rem;
    border-block-end: 1px solid var(--seam, #222c42);
    background: var(--hull, #0f1523);
  }

  .viewport__gauge {
    display: flex;
    align-items: center;
    gap: 0.45rem;
  }

  .viewport__label {
    font-size: var(--text-2xs, 0.6875rem);
    letter-spacing: var(--track-etched, 0.14em);
    text-transform: uppercase;
    color: var(--ink-dim, #a79fb5);
  }

  .viewport__rotate {
    line-height: 1;
  }

  /* The measurement. Pushed to the end of the strip because it is the answer, not a
     control — you read it after you have touched something. */
  .viewport__readout {
    margin: 0 0 0 auto;
    padding: 0.15rem 0.5rem;
    border: 1px solid var(--seam, #222c42);
    border-radius: 999px;
    background: var(--hull-lit, #172031);
    font-family: var(--font-data, ui-monospace, monospace);
    font-size: var(--text-2xs, 0.6875rem);
    font-variant-numeric: tabular-nums;
    letter-spacing: 0.02em;
    white-space: nowrap;
    color: var(--ink-dim, #a79fb5);
  }

  /* Off-screen but not `display: none` and not `visibility: hidden`: either of those
     takes the text out of the accessibility tree, and a live region cannot announce a
     change it is not allowed to have. */
  .viewport__spoken {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
    border: 0;
  }

  /* Selected is LIVE, so selected is thruster. Brass is the aparté signature and is not
     a second accent — see the same rule in App.svelte. */
  .viewport__bar :global(.aparte-btn[aria-pressed='true']) {
    background: color-mix(in srgb, var(--thruster, #ff3e00) 15%, transparent);
    border-color: color-mix(in srgb, var(--thruster, #ff3e00) 65%, transparent);
    color: var(--thruster-lit, #ff5c26);
  }

  .viewport__bar :global(.aparte-btn[disabled]) {
    opacity: 0.4;
    cursor: not-allowed;
  }

  /* ── The stage ─────────────────────────────────────────────────────────── */

  .viewport__area {
    position: relative;
    flex: 1;
    min-width: 0;
    min-height: 0;
  }

  /*
   * Space behind the glass: the void, ruled with a hairline grid.
   *
   * The grid is what makes the frame read as an object sitting IN something rather than
   * as a white rectangle floating on black — and at 40% zoom it is also the only thing on
   * screen at a known scale, so the eye has a ruler. It is deliberately near-invisible:
   * one step off the void, in the seam colour.
   */
  .viewport__stage {
    position: absolute;
    inset: 0;
    display: flex;
    overflow: auto;
    background-color: var(--void, #070a12);
    background-image:
      linear-gradient(to right, var(--seam, #222c42) 0 1px, transparent 1px 100%),
      linear-gradient(to bottom, var(--seam, #222c42) 0 1px, transparent 1px 100%);
    background-size: 32px 32px;
    /* Left at the default `scroll`, which on a scroll container means the background is
       painted against the BOX and does not move with the content: panning slides the
       frame across a fixed rule, which is what a rule is for. */
    overscroll-behavior: contain;
  }

  .viewport__stage.is-pannable {
    cursor: grab;
  }

  .viewport__stage.is-panning {
    cursor: grabbing;
  }

  /*
   * `margin: auto`, not `justify-content: center`.
   *
   * Centring a flex item that is LARGER than its scroll container with `justify-content`
   * puts the overflow on both sides and makes the top-left half of it unreachable — the
   * scroll origin is the container's start edge, and there is nothing before it. Auto
   * margins resolve to zero when there is no free space, so the same declaration centres
   * a small frame and pins a large one where it can be scrolled to in full.
   */
  .viewport__bezel {
    position: relative;
    flex: none;
    margin: auto;
    box-sizing: border-box;
    padding: 8px; /* GASKET */
    border: 1px solid var(--seam, #222c42);
    border-radius: 10px;
    background: var(--hull-lit, #172031);
    /* A canopy sitting in front of the void: a real drop shadow, a lit hairline on the
       inside of the seal, and a thin cold rim on the outside so the housing separates
       from the grid even where the two are nearly the same value. */
    box-shadow:
      0 18px 44px -12px rgb(0 0 0 / 0.75),
      0 2px 10px rgb(0 0 0 / 0.45),
      inset 0 0 0 1px color-mix(in srgb, var(--thruster, #ff3e00) 12%, transparent);
  }

  /* Filling the pane is not a device: no rounded housing, no floating shadow, just the
     glass and its seal. */
  .viewport__bezel.is-fill {
    border-radius: 4px;
    box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--thruster, #ff3e00) 10%, transparent);
  }

  /*
   * The scaled picture.
   *
   * `transform` and not `width`, which is the whole point of this component: the wrapper
   * is laid out at the document's REAL size and only the painted result is shrunk, so the
   * page inside keeps the viewport it was given. `transform-origin` is the top-left
   * because the housing above is sized from the same corner.
   */
  .viewport__glass {
    position: relative;
    transform-origin: top left;
    overflow: hidden;
    background: #ffffff;
  }

  .viewport__frame {
    display: block;
    width: 100%;
    height: 100%;
    border: 0;
    background: #ffffff;
    transition: opacity var(--tick-fast, 0.12s) ease;
  }

  /* Not a spinner: the old view steps back while the new one is on its way. */
  .viewport__frame.is-busy {
    opacity: 0.72;
  }

  /* While the glass is being dragged, the page inside it stops answering the pointer.
     Pointer capture already keeps the events on the grip, but without this the previewed
     document lights up its own hover states under a cursor that is resizing a window. */
  .viewport__frame.is-inert {
    pointer-events: none;
  }

  /* ── The grips ─────────────────────────────────────────────────────────── */

  /*
   * Sized in stage pixels on the housing, so they are the same 10px target whether the
   * picture is at 100% or at 25%. Quiet until the pointer is near them, lit while they
   * have focus — they are controls, and orange is what live looks like here.
   */
  .viewport__grip {
    position: absolute;
    padding: 0;
    border: 0;
    border-radius: 999px;
    background: color-mix(in srgb, var(--ink-dim, #a79fb5) 34%, transparent);
    opacity: 0.5;
    transition:
      opacity var(--tick, 180ms) ease,
      background-color var(--tick, 180ms) ease;
    touch-action: none;
  }

  .viewport__grip--e {
    inset-inline-end: 1px;
    inset-block-start: 50%;
    width: 5px;
    height: 34px;
    margin-block-start: -17px;
    cursor: ew-resize;
  }

  .viewport__grip--s {
    inset-block-end: 1px;
    inset-inline-start: 50%;
    width: 34px;
    height: 5px;
    margin-inline-start: -17px;
    cursor: ns-resize;
  }

  .viewport__grip--se {
    inset-inline-end: 1px;
    inset-block-end: 1px;
    width: 12px;
    height: 12px;
    border-radius: 3px;
    cursor: nwse-resize;
  }

  .viewport__bezel:hover .viewport__grip {
    opacity: 0.9;
  }

  .viewport__grip:hover,
  .viewport__grip:focus-visible {
    opacity: 1;
    background: var(--thruster, #ff3e00);
  }

  .viewport__grip:focus-visible {
    outline: 2px solid var(--thruster, #ff3e00);
    outline-offset: 2px;
  }

  /* ── Overlays ──────────────────────────────────────────────────────────── */

  /*
   * Transparent to the pointer by default, so a card drawn here never eats a click meant
   * for the previewed page. Anything inside it that IS interactive turns them back on.
   */
  .viewport__overlay {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  .viewport__overlay :global(> *) {
    pointer-events: auto;
  }

  @media (max-width: 44rem) {
    /* The strip has to fit before it has to be charming. Nothing is lost to a screen
       reader: the labels are `aria-hidden` and every group keeps its `aria-label`. */
    .viewport__label {
      display: none;
    }

    .viewport__bar {
      gap: 0.35rem 0.5rem;
      padding: 0.35rem 0.5rem;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .viewport__frame,
    .viewport__grip {
      transition: none;
    }
  }
</style>
